config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #match ':controller(/:action(/:id))(.:format)'
  resources :items do
    get :upvote,    on: :member
    get :expensive, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

  has_many :comments, as: :commentable
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user
  has_many   :positions
  has_many   :items, through: :positions
  #has_and_belongs_to_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :price, numericality: { greater_than: 0, allow_nil: true }
  validates :name, :description, presence: true
s
  #has_and_belongs_to_many :carts
  has_many :carts, through: :positions
  has_many :positions

  has_many :comments, as: :commentable
  #belongs_to :category

  #after_initialize { puts "initialized" } # Item.new; Item.first
  #after_save       { puts "saved" } # Item.save; Item.create; item.update_attributes()
  #after_create     { ItemMailer.new_item_created(self).deliver }
  #after_create     { category.inc(:items_count, 1) }
  #after_update     { puts "updated" }
  #after_destroy    { category.inc(:items_count, -1) } # item.destroy

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
end

app/models/position.rb
class Position < ApplicationRecord

  belongs_to :item
  belongs_to :cart

end

app/models/user.rb
class User < ApplicationRecord

  has_one :cart
  has_many :orders
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  protect_from_forgery with: :exception

  private

  def render_403
    render file: "public/403.html", status: 403
  end

  def render_404
    render file: "public/404.html", status: 404
  end

  def chack_if_admin
    render_403 unless params[:admin]
    #render text: "Access denied", status: 403 unkess params[:admin]
  end

end

app/controllers/blog_post_controller.rb
class BlogPostController < ApplicationController

  private

  def resource_params
    params.require(:resource).permit(:title, :body)
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  private

  def resource_params
    params.require(:resource).permit(:body, :user_id, :commentable_id, :commentable_type)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :chack_if_admin, only: [:edit, :update, :new, :create, :destroy]

  def index
    @items = Item.all
  end

  def expensive
    @items = Item.where("price > 1000")
    render "index"
  end

  # /items/1 GET
  def show
    unless @item
      render text: "Page not found", status: 404
    end
  end

  # items/new GET
  def new
    @item = Item.new
  end

  # /item/1/edit GET
  def edit

  end

  # /items POST
  def create
    @item = Item.create(item_params)
      if @item.errors.empty?
        redirect_to item_path(@item)
      else
        render "new"
      end

   # @item = Item.create(params[:item])
    #if @item.errors.empty?
     # redirect_to item_path(@item)
    #else
      #render "new"
    #end
  end

  def update

    @item.update_attributes(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render "edit"
    end
  end

  #/items DELETE
  def destroy

    @item.destroy
    redirect_to action: "index"
  end

  def upvote
    @item.increment!(:votes_count)
    redirect_to action: :index
  end

  private

  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless @item
  end

  def item_params
    params.permit(:name, :price, :real, :weight, :description)
  end


end

app/controllers/order_controller.rb
class OrderController < ApplicationController

  private

  def resource_params
    params.require(:resource).permit(:user, :user_id)
  end
end

app/controllers/position_controller.rb
class PositionController < ApplicationController

  private

  def resource_params
    params.require(:resource).permit(:item_id, :cart_id, :quantity)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  private

  def resource_params
    params.require(:resource).permit(:login)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_post_helper.rb
module BlogPostHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/position_helper.rb
module PositionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/items/_form.html.erb
<p>Цена: <br/><%= f.text_field :price %></p>
<p>Название: <br/><%= f.text_field :name %></p>
<p>Описание: <br/><%= f.text_field :description %></p>
<p>Вес: <br/><%= f.text_field :weight %></p>

app/views/items/edit.html.erb
<h1>Edit items</h1>

<%= form_for @item do |f| %>

    <%= render partial: "form", locals: { f: f } %>

    <p><%= f.submit "Сохранить товар" %></p>

<% end %>

app/views/items/index.html.erb
<h1>Items</h1>

<% if @items.empty? %>
    <b>No items in store</b>
<% else %>
<table>
    <tr>
      <th>item_id</th>
      <th>Name</th>
      <th>Price</th>
      <th></th>
      <th></th>
    </tr>

<% @items.each do |i| %>
    <tr>
      <td><%= i.id %></td>
      <td><%= link_to i.name, item_path(i) %></td>
      <td><%= i.price %> грн.</td>
      <td><%= link_to "Удалить", i, method: :delete, data: {confirm: "Точно удалить?" } %></td>
      <td>Рейтинг: <%= i.votes_count %><%= link_to "+", upvote_item_path(i) %></td>
    </tr>
  <% end %>
      </table>

<% end %>

app/views/items/new.html.erb
<h1>Create new items</h1>

<%= form_for @item do |f| %>

    <%= render partial: "form", locals: { f: f } %>

    <p><%= f.submit "Создать товар" %></p>

<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<ul>
  <li><%= @item.price %>грн.</li>
  <li><%= @item.description %></li>
  <li>Вес: <%= @item.weight %>кг.</li>
</ul>